Japanese translation of TOUR OF SCALA mixin-class-composition
take2webservice/docs.scala-lang pull request #10
Opened 2019-03-14 09:11 UTC by take2webservice

2019-03-14 13:43 UTC, tockri requested changes
mixinってtraitのことなんですねー。俺たちは雰囲気でmixinを使っていた。

2019-03-14 13:43 UTC, tockri commented on _ja/tour/mixin-class-composition.md
> +ミックスインは複数のトレイトを利用し1つのクラスを構成することです。
```suggestion
ミックスインはクラスを構成するのに使われるトレイトです。
```
あとの例でミックスイン、一つしか使ってないので…

2019-03-14 13:43 UTC, tockri commented on _ja/tour/mixin-class-composition.md
> +`StringIterator`は`String`を受け取り、Stringを反復処理するために使うことができます。
```suggestion
`StringIterator`は`String`を受け取り、そのStringを反復処理するために使われます。
```

2019-03-14 13:43 UTC, tockri commented on _ja/tour/mixin-class-composition.md
> +（例：Stringに特定の文字列が含まれているかを確認するために）
```suggestion
（例：Stringに特定の文字が含まれているかを確認するために）
```

2019-03-14 13:43 UTC, tockri commented on _ja/tour/mixin-class-composition.md
> +このトレイトは(`while (hasNext)`で)要素がある限り、与えられた関数 `f: T => Unit`を次の要素(`next()`)に対し連続して呼び出す`foreach`メソッドのみを実装します。
```suggestion
このトレイトは(`while (hasNext)`で)要素がある限り、与えられた関数 `f: T => Unit`を次の要素(`next()`)に対し連続して呼び出す`foreach`メソッドを実装しています。
```

2019-03-14 13:43 UTC, tockri commented on _ja/tour/mixin-class-composition.md
> +なぜなら`RichIterator`はトレイトであり、`RichIterator`はAbsIteratorの抽象メンバーを実装する必要がないからです。
```suggestion
`RichIterator`はトレイトなので、`RichIterator`はAbsIteratorの抽象メンバーを実装する必要がありません。
```
文頭でBecauseって始めるのはあんまり上手じゃないって英語の先生が言ってた…

2019-03-14 13:43 UTC, tockri commented on _ja/tour/mixin-class-composition.md
> +`StringIterator`と`RichIterator`の機能を1つのクラスに組み合わせたい場合、
```suggestion
`StringIterator`と`RichIterator`の機能を1つのクラスに組み合わせてみましょう。
```

2019-03-14 13:43 UTC, tockri commented on _ja/tour/mixin-class-composition.md
> +新しいクラス`RichStringIter`は`StringIterator`をスーパークラスとし、`RichIterator`をミックスインします。
```suggestion
新しいクラス`RichStringIter`は`StringIterator`をスーパークラスとし、`RichIterator`をミックスインとしています。
```

2019-03-15 00:59 UTC, take2webservice commented on _ja/tour/mixin-class-composition.md
> +なぜなら`RichIterator`はトレイトであり、`RichIterator`はAbsIteratorの抽象メンバーを実装する必要がないからです。
なるほど！気をつけねば！

2019-03-15 01:00 UTC, merged