Japanese translation of TOUR OF SCALA nested-functions
take2webservice/docs.scala-lang pull request #12
Opened 2019-03-15 08:53 UTC by take2webservice

2019-03-23 16:00 UTC, tockri requested changes
これめっちゃ短いんですね！あと２つぐらいやります！

2019-03-23 16:00 UTC, tockri commented on _ja/tour/nested-functions.md
> +Scalaではネストメソッドの定義ができます。
```suggestion
Scalaではメソッドの定義をネストすることができます。
```

2019-03-23 16:00 UTC, tockri commented on _ja/tour/nested-functions.md
> +以下のオブジェクトは与えられた数値の階乗を演算するための`factorial`メソッドを提供します。
```suggestion
以下のコードは与えられた数値の階乗を計算するための`factorial`メソッドを提供します。
```
もとの英語、どこにもobjectないのになんでobjectって書いたんや…
たぶん「次のやつは」みたいな感じなんだろうけどScalaのツアーでobjectって書いたらobjectのことだと思うやん…

2019-03-28 07:29 UTC, take2webservice commented on _ja/tour/nested-functions.md
> +以下のオブジェクトは与えられた数値の階乗を演算するための`factorial`メソッドを提供します。
言われてみればサンプルコードにオブジェクトなかったでござる…

2019-03-28 07:29 UTC, merged