Japanese translation of TOUR OF SCALA multiple-parameter-lists
take2webservice/docs.scala-lang pull request #13
Opened 2019-03-16 06:46 UTC by take2webservice

2019-03-23 18:09 UTC, tockri requested changes
https://github.com/take2webservice/docs.scala-lang/blob/master/_tour/multiple-parameter-lists.md
と見比べてみたらどうも後半部分が違うものと混じっちゃってるみたいな感じなので、いったんここまでにしておきます。

2019-03-23 18:09 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +こちらはScalaのコレクションのドキュメントの[走査可能トレイト](/overviews/collections/trait-traversable.html) で定義された例になります。
```suggestion
こちらはScalaのコレクションの[Traversable](/overviews/collections/trait-traversable.html) トレイトで定義されている実例です。
```

2019-03-23 18:09 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +`foldLeft`は初期値`z`とこの走査可能な全ての要素に対し左から右に二項演算子`op`を適用していきます。
```suggestion
`foldLeft`は初期値`z`とこのtraversableの全ての要素に対し左から右に二項演算子`op`を適用していきます。
```

2019-03-23 18:09 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +複数パラメータリストにはより冗長な読み出し構文があり、それゆえ控えめに使う必要があります。
```suggestion
```
なんか意味が通らないなあと思って
https://docs.scala-lang.org/tour/multiple-parameter-lists.html
を見てみたら、この文無くなってました。たぶんなんかの間違いじゃないかなーと思います。

2019-03-23 18:09 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +推奨されるユースケースは次の通りです。
```suggestion
### ユースケース
推奨されるユースケースは次の通りです。
```
本来こうなるべきだったらしい。

2019-03-23 18:09 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +#### 単一機能パラメータ
```suggestion
#### 単一の関数パラメータ
```

2019-03-23 18:09 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +   単一機能パラメータの場合、上記の`foldLeft`のケースでの`op`のように、複数パラメータリストを使うと簡潔な構文でメソッドに無名関数を渡すことができます。
```suggestion
   関数のパラメータが一つの場合、上記の`foldLeft`のケースでの`op`のように、複数パラメータリストを使うと簡潔な構文でメソッドに無名関数を渡すことができます。
```

2019-03-23 18:09 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +   複数パラメータリストを使うことで、以下のようにコードをより簡潔にすることができ、Scalaの型インターフェースの利点を享受できることに注意してください。
```suggestion
   複数パラメータリストを使うことで、Scalaの型インターフェースの利点を享受でき、以下のようにコードをより簡潔にすることができるのです。
```
Note that は強調してるだけなので、注意してくださいって訳しちゃうとちょっと違う意味がついちゃいます。なので、文末でちょっと強調っぽくしてみました。

2019-03-23 18:09 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +   それはカリー化されていない定義ではできません。
```suggestion
   これはカリー化されていない定義ではできません。
```
文を分けて訳すのいい感じです。

2019-03-23 18:09 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +   上記の`numbers.foldLeft(0)(_ + _)`はパラーメーター`z`を固定し、以下のように部分函数を渡し、再利用することができます。
以下、なんかおかしいと思って
https://github.com/take2webservice/docs.scala-lang/blob/master/_tour/multiple-parameter-lists.md
を見てみましたが、もとの英文がなにか間違ってるっぽい？
見直してみてもらえますか？

2019-04-02 06:35 UTC, closed without merging

2019-04-02 06:35 UTC, take2webservice commented
大元のファイルが変更されているので一旦閉じます