Japanese translation of TOUR OF SCALA ja_case-classes
take2webservice/docs.scala-lang pull request #14
Opened 2019-03-16 08:06 UTC by take2webservice

2019-03-24 16:00 UTC, tockri requested changes
おわりました！

2019-03-24 16:00 UTC, tockri commented on _ja/tour/case-classes.md
> +ケースクラスはイミュータブルなデータを作ることができます。
```suggestion
ケースクラスは不変なデータを作るのに適しています。
```
https://github.com/take2webservice/docs.scala-lang/blob/translation-tour-ja/_ja/tour/basics.md
で「不変」と訳してるので、揃えました。

2019-03-24 16:00 UTC, tockri commented on _ja/tour/case-classes.md
>  ## Defining a case class
```suggestion
## ケースクラスの宣言
```

2019-03-24 16:00 UTC, tockri commented on _ja/tour/case-classes.md
> +これはケースクラスが標準でオブジェクトの建造を処理する`apply`メソッドを保有するためです。
```suggestion
これはケースクラスがオブジェクトの生成を行う`apply`メソッドを標準で保有するためです。
```
建造は、ちょっと重いかなー。
あとapplyメソッドがあるのはケースクラスが自動で生成するコンパニオンオブジェクトなんで、原文にたいしてちょっとモヤっとするw

2019-03-24 16:00 UTC, tockri commented on _ja/tour/case-classes.md
> +パラメータを利用しケースクラスを作る時は、パラメータはパブリック定数となります。
```suggestion
パラメータ有りでケースクラスを作ると、パラメータはパブリックの`val`となります。
```
定数じゃなくてパラメータなので、素直に原文のままがよさそうです。どうしても変えるなら「不変なメンバー」ぐらいですかね。

2019-03-24 16:00 UTC, tockri commented on _ja/tour/case-classes.md
> +ケースクラスでは`var`も使うことができますが、お勧めできません。
```suggestion
ケースクラスでは`var`も使うことができますが、推奨されません。
```

2019-03-24 16:00 UTC, tockri commented on _ja/tour/case-classes.md
> +`message4`の定数recipientは`message5`の定数senderとして使われますが、`message4`の定数`body`は直接コピーされます。
```suggestion
`message4`のrecipientは`message5`のsenderとして使われますが、`message4`の定数`body`は直接コピーされます。
```

2019-03-28 07:55 UTC, take2webservice commented on _ja/tour/case-classes.md
> +これはケースクラスが標準でオブジェクトの建造を処理する`apply`メソッドを保有するためです。
なるほどなるほど
生成とかでいいんですねー

2019-03-28 07:56 UTC, take2webservice commented on _ja/tour/case-classes.md
> +パラメータを利用しケースクラスを作る時は、パラメータはパブリック定数となります。
素直に`val`とかで良いんですねー
宣言方法なイメージなのでなんか慣れなくてー

2019-03-28 07:57 UTC, merged