Japanese translation of TOUR OF SCALA pattern-matching
take2webservice/docs.scala-lang pull request #15
Opened 2019-03-17 08:10 UTC by take2webservice

2019-03-19 18:08 UTC, tockri requested changes
1つ目おわりました！

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +パターンマッチングはパターンに対応した値をチェックするための機能です。
```suggestion
パターンマッチングはパターンに対応させて値をチェックするための機能です。
```

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +マッチに成功すれば、はその構成要素のパーツを一つの値に分解することもできます。
```suggestion
マッチに成功すれば、一つの値をその構成要素のパーツに分解することもできます。
```
逆だったw

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +マッチ表現は値、キーワード`match`と最低でも1つの`case`句を持ちます。
```suggestion
マッチ式は値、キーワード`match`と最低でも1つの`case`句を持ちます。
```
expression = 式（値を返すやつ）、statement = 文（値を返さないやつ） と訳されることが多いはずなので統一していきたい感じです。

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +上記の`val x`は0から10の間のランダムな整数です。`x`は`match`演算子の左側被演算子となり、右側被演算子は4つのケースで表現されます。
```suggestion
上記の`val x`は0から10の間のランダムな整数です。`x`は`match`演算子の左オペランドで、右側は4つのケースを持つ式です。
```
被演算子よりはオペランドの方をよく見かける気がします。どっちにしてもわかりにくい言葉だけど。

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +マッチ表現は値を持ちます。
```suggestion
マッチ式は値を持ちます。
```

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +このマッチ表現はString型を持ちます、なぜなら全てのケースはStringを返します。
```suggestion
全てのケースがStringを返すので、このマッチ式はString型を持ちます。
```

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +そのため関数`matchTest`はStringを返します。
```suggestion
したがって関数`matchTest`はStringを返します。
```

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +`Notification`はケースクラスで実装された`Email`、 `SMS`、 そして`VoiceRecording`3つの具体的なお知らせの種類を持つ抽象スーパークラスです。
```suggestion
`Notification`は抽象スーパークラスで、3つの具象クラスを持ちます。ケースクラスとして実装した`Email`、 `SMS`、 `VoiceRecording`です。
```

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +関数`showNotification`は抽象型`Notification`のパラメータとして受け取り、`Notification` の種類とマッチします（すなわち`Email`、`SMS`、または `VoiceRecording`のいずれであるかを解決します）。
```suggestion
関数`showNotification`は抽象型`Notification`をパラメータとして受け取り、`Notification` の種類とマッチします（すなわち`Email`、`SMS`、または `VoiceRecording`のいずれであるかを判定します）。
```

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +ただ`if <boolean expression>`をパターンの後ろに追加するだけです。
```suggestion
ただ`if <boolean 式>`をパターンの後ろに追加するだけです。
```

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +      showNotification(other) // 特別なものではなく、オリジナルのshowNotification関数に委任します。
```suggestion
      showNotification(other) // 特別なものではなく、オリジナルのshowNotification関数に委譲します。
```
delegateはC#とかで委譲って書かれることが多いので

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +トレイトとクラスは全てのサブタイプは同一ファイル内で宣言されているべきとする`sealed`でマークすることができます。
```suggestion
トレイトとクラスに`sealed`をつけると、全てのサブタイプは同一ファイル内で宣言されなければならないという意味になります。
```
関係詞を訳す時って、後ろ→前の順にひっくり返して訳すと主語と述語が離れすぎて読みにくくなるので、自然に前→後ろの順にしてやれば読む方も楽になると最近気づきました。
which を「するとそれが」、where を「そこで」のように接続詞として訳すと自然な日本語になるし、たぶん英語話者もそういう感覚で読んでるんだろうなって。

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +これは全てのサブタイプは既知であると保証します。
```suggestion
これは全てのサブタイプは既知であることを保証します。
```

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +Scalaのパターンマッチング文は[ケース型](case-classes.html)を通して代数型の表現のマッチングの際に最も役立ちます。
```suggestion
Scalaのパターンマッチング文は[ケースクラス](case-classes.html)で表現される代数型のマッチングに最も役立ちます。
```

2019-03-19 18:08 UTC, tockri commented on _ja/tour/pattern-matching.md
> +Scalaは[抽出子オブジェクト](extractor-objects.html)で`unapply`メソッドを利用した独立したケースクラスのパターン定義ができます。
```suggestion
Scalaでは[抽出子オブジェクト](extractor-objects.html)の`unapply`メソッドを使うと、ケースクラスのパターンを独自に定義することもできます。
```

2019-03-20 01:50 UTC, take2webservice commented on _ja/tour/pattern-matching.md
> +マッチ表現は値、キーワード`match`と最低でも1つの`case`句を持ちます。
おー、expression = 式って認識がなかったので勉強になります！

2019-03-20 01:53 UTC, take2webservice commented on _ja/tour/pattern-matching.md
> +マッチに成功すれば、はその構成要素のパーツを一つの値に分解することもできます。
惜しいw

2019-03-20 01:57 UTC, take2webservice commented on _ja/tour/pattern-matching.md
> +      showNotification(other) // 特別なものではなく、オリジナルのshowNotification関数に委任します。
なるほどなるほど

2019-03-20 01:59 UTC, take2webservice commented on _ja/tour/pattern-matching.md
> +Scalaのパターンマッチング文は[ケース型](case-classes.html)を通して代数型の表現のマッチングの際に最も役立ちます。
なるほどなるほど
訳しててよく分からんとなってました

2019-03-20 02:01 UTC, take2webservice commented on _ja/tour/pattern-matching.md
> +トレイトとクラスは全てのサブタイプは同一ファイル内で宣言されているべきとする`sealed`でマークすることができます。
なるほど！確かに読みやすいです！
無理に直訳しなくても良いんだなーとなり始めました！

2019-03-20 02:07 UTC, take2webservice commented on _ja/tour/pattern-matching.md
> +Scalaは[抽出子オブジェクト](extractor-objects.html)で`unapply`メソッドを利用した独立したケースクラスのパターン定義ができます。
こっちの方がテンポよく読めますねー

2019-03-20 02:07 UTC, merged