Japanese translation of TOUR OF SCALA singleton-objects
take2webservice/docs.scala-lang pull request #16
Opened 2019-03-20 03:45 UTC by take2webservice

最後の方にある「static forwarding」って良い訳ないでしょうか？？

2019-03-24 17:36 UTC, tockri requested changes
static forwarding、うまい日本語ないし、たぶん英語話者もちゃんと知るまでは「どういう意味や！？」ってなると思うし、このままでいいんじゃないかなーと思います。

2019-03-24 17:36 UTC, tockri commented on _ja/tour/singleton-objects.md
> +それは遅延評価valのように参照された際に遅れて作られます。
```suggestion
それはlazy valのように参照された際に遅れて作られます。
```

2019-03-24 17:36 UTC, tockri commented on _ja/tour/singleton-objects.md
> +オブジェクトはトップレベルの値のようにシングルトンです。
```suggestion
トップレベルのオブジェクトは、シングルトンです。
```

2019-03-24 17:36 UTC, tockri commented on _ja/tour/singleton-objects.md
> +エンクロージングクラス（外部クラス）のメンバーやローカルの値のように、オブジェクトはまるで遅延評価valのように振る舞います。
```suggestion
クラスのメンバーやローカル変数としてのオブジェクトは、lazy valと全く同じように振る舞います。
```
enclosing classは、そのオブジェクトを取り囲んでいるclassということなので、
```
class Foo {
  object Bar {}
}
```
みたいなケースで、とくに訳さなくていいと思います。

2019-03-24 17:36 UTC, tockri commented on _ja/tour/singleton-objects.md
> +注意：`オブジェクト`がトップレベルではないが、他のクラスやオブジェクトを必要とする時、オブジェクトは他のメンバーのように"経路依存性"があります。
```suggestion
注意：`オブジェクト`がトップレベルでなく、他のクラスやオブジェクトにネストしている時、オブジェクトは他のメンバーのように"パス依存性"があります。
```

2019-03-24 17:36 UTC, tockri commented on _ja/tour/singleton-objects.md
> +これは2種類の飲み物`牛乳 クラス`と`オレンジジュース クラス`が与えられた場合、クラスメンバーの`栄養素 object`はエンクロージングクラス、すなわち牛乳またはオレンジジュースのいずれかのインスタンスに依存することを意味します。
```suggestion
これは2種類の飲み物`class 牛乳`と`class オレンジジュース`が与えられた場合、クラスメンバーの`object 栄養素`はそれが属するインスタンス、すなわち牛乳またはオレンジジュースのいずれかに依存することを意味します。
```

2019-03-24 17:36 UTC, tockri commented on _ja/tour/singleton-objects.md
> +逆にクラスはオブジェクトのコンパニオンクラスとなります。
```suggestion
逆にそのクラスはオブジェクトのコンパニオンクラスと呼ばれます。
```

2019-03-24 17:36 UTC, tockri commented on _ja/tour/singleton-objects.md
> +コンパニオンクラスのインスタンスの固有ではないメソッドや値にはコンパニオンオブジェクトを使います。
```suggestion
コンパニオンクラスのインスタンスに特定されないメソッドや値にはコンパニオンオブジェクトを使います。
```
固有はuniqueとかidenticalなのでちょっと意味が違いますね。specificはそのインスタンスごとに別々に特定された、という感じだと思いますが、こういうの訳すのわかんないですねー

2019-03-24 17:36 UTC, tockri commented on _ja/tour/singleton-objects.md
> +エラー解析のケース内では`Email`インスタンスを`Option[Email]`として返します。
```suggestion
パースエラーの場合も考えて、返り値の型を`Option[Email]`とします。
```

2019-03-24 17:36 UTC, tockri commented on _ja/tour/singleton-objects.md
> +これはコンパニオンクラスを定義していなかったとしても起きます。
```suggestion
これはコンパニオンクラスを自分で定義していなかったとしても起きます。
```

2019-03-28 08:41 UTC, take2webservice commented on _ja/tour/singleton-objects.md
> +エラー解析のケース内では`Email`インスタンスを`Option[Email]`として返します。
「in case of」で「〜の場合」ってイデオムなんですねー

2019-03-28 08:41 UTC, merged