Translation tour ja multiple parameter lists
take2webservice/docs.scala-lang pull request #17
Opened 2019-04-02 06:38 UTC by take2webservice

翻訳元はこちらになります。
https://github.com/scala/docs.scala-lang/blob/master/_tour/multiple-parameter-lists.md

2019-04-06 16:10 UTC, tockri requested changes
お疲れ様でした。ちょっとsingle functional parameterが訳しにくいですねえ。
パラメータリストの中身が関数１つだけであれば、型を省略できるって話なんですが…日本語の名詞をうまく当てるのは無理な気がする。

2019-04-06 16:10 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +こちらはScalaのコレクションAPIにて`TraversableOnce`の特徴が定義された例です。
```suggestion

```
削除し忘れっぽい

2019-04-06 16:10 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +#### 単一の関数パラメータ
```suggestion
#### 一つだけの関数パラメータ
```
functional parameterは関数をパラメータとして渡すことを指してるのですが、これなんて日本語にすればいいんだろう…

2019-04-06 16:10 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +関数のパラメータが一つの場合、上記の`foldLeft`のケースでの`op`のように、複数パラメータリストを使うと簡潔な構文でメソッドに無名関数を渡すことができます。
```suggestion
パラメータに関数を一つだけ渡すのであれば、上記の`foldLeft`のケースでの`op`のように、複数パラメータリストを利用して簡潔な構文でメソッドに無名関数を渡すことができます。
```

2019-04-06 16:10 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +らScalaコンパイラは関数のパラメータの型推論することができないので、このようなことは単一パラメータリストではできません。
```suggestion
単一のパラメータリストではScalaコンパイラが関数のパラメータを型推論できないので、このようなことはできません。
```

2019-04-06 16:10 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +特定のパラメータを`implicit`として指定するには、それらはそれら自身を`暗黙の`パラメーターリストに置かなければなりません。
```suggestion
特定のパラメータだけを`implicit`として指定するには、`implicit`のパラメーターリストに入れなければなりません。
```

2019-04-09 04:27 UTC, take2webservice commented on _ja/tour/multiple-parameter-lists.md
> +#### 単一の関数パラメータ
「パラメータが関数型のオブジェクト1つ」のとかですかね？？
んー、しっくり来ない…

2019-04-09 04:28 UTC, take2webservice commented on _ja/tour/multiple-parameter-lists.md
> +らScalaコンパイラは関数のパラメータの型推論することができないので、このようなことは単一パラメータリストではできません。
大分わかりやすいっす！！

2019-04-09 14:01 UTC, tockri commented on _ja/tour/multiple-parameter-lists.md
> +#### 単一の関数パラメータ
「関数パラメータ」がたぶん違うんですね。
```
### パラメータに関数を一つ渡す場合
```
とか長く書いちゃえばいいと思いました。

2019-04-09 15:32 UTC, take2webservice commented on _ja/tour/multiple-parameter-lists.md
> +#### 単一の関数パラメータ
なるほど！ありがとうございます！

2019-04-09 15:36 UTC, take2webservice commented on _ja/tour/multiple-parameter-lists.md
> +#### 単一の関数パラメータ
```suggestion
#### パラメータに関数を一つ渡す場合
```

2019-04-09 15:36 UTC, take2webservice commented on _ja/tour/multiple-parameter-lists.md
> +#### 単一の関数パラメータ
関数パラメータだと日本語的にしっくりこないので

2019-04-09 15:37 UTC, merged