Japanese translation of TOUR OF SCALA extractor-objects
take2webservice/docs.scala-lang pull request #20
Opened 2019-04-02 09:17 UTC by take2webservice

2019-04-07 02:08 UTC, tockri requested changes
まだunapplyを自分で書いたことはないけど、理屈は理解しておいたほうがいいですよねー。

2019-04-07 02:08 UTC, tockri commented on _ja/tour/extractor-objects.md
> + `CustomerID("Sukyoung")`を呼び出すとき、これは`CustomerID.apply("Sukyoung")`を呼び出す速記構文になります。
```suggestion
 `CustomerID("Sukyoung")`は、`CustomerID.apply("Sukyoung")`を短く書く構文です。
```
日本語で速記構文って書くと、なんか専門用語っぽく見えちゃうけど実際そんな用語はないので、さらっと。

2019-04-07 02:08 UTC, tockri commented on _ja/tour/extractor-objects.md
> + `case CustomerID(name) => println(name)`を呼び出すとき、unapplyメソッドを呼び出しています。
```suggestion
 `case CustomerID(name) => println(name)`では、unapplyメソッドを呼んでいます。
```
さらっと書いちゃったほうが読みやすいかなーと思いました。

2019-04-07 02:08 UTC, tockri commented on _ja/tour/extractor-objects.md
> +unapplyメソッドが値を供給する場合、新しい変数を導くパターンを使うことで値定義ができるので、エクストラクタは変数の初期化に使うことができます。
```suggestion
値を定義する文で、パターン中に新しい変数を使うことができるので、エクストラクタは変数を初期化するのに使えます。この場合unapplyメソッドが初期値を与えます。
```

2019-04-09 04:39 UTC, take2webservice commented on _ja/tour/extractor-objects.md
> +unapplyメソッドが値を供給する場合、新しい変数を導くパターンを使うことで値定義ができるので、エクストラクタは変数の初期化に使うことができます。
あー、なるほどthe valueがa new variableを指してるんですね！

2019-04-09 04:39 UTC, merged