Japanese translation of TOUR OF SCALA for-comprehensions
take2webservice/docs.scala-lang pull request #22
Opened 2019-04-03 13:56 UTC by take2webservice

2019-04-07 11:15 UTC, tockri requested changes
最後のyield書かなければUnit返すの、知らなかった！

2019-04-07 11:15 UTC, tockri commented on _ja/tour/for-comprehensions.md
> +Scalaは*シーケンス内包表記*を表現するための軽量記法を提供します。
```suggestion
Scalaは*シーケンス内包表記*を表現するための軽量な記法を提供します。
```
テクニカルタームっぽく見えないようにしてみました。

2019-04-07 11:15 UTC, tockri commented on _ja/tour/for-comprehensions.md
> +`enumerators`がセミコロンで区切られたEnumeratorのリストを参照する場合、内含表記には`for (enumerators) yield e`の形式があります。
```suggestion
内含表記は`for (enumerators) yield e`という形をとります。`enumerators`はセミコロンで区切られたEnumeratorのリストを指します。
```
接続詞のwhereはたいていの場合、書いてある順番をひっくり返さないほうが意味を取りやすくなりますね。

2019-04-07 11:15 UTC, tockri commented on _ja/tour/for-comprehensions.md
> +  yield user.name  // すなわちこれをリストに追加する
```suggestion
  yield user.name  // これをリストに追加する
```
日本語の接続詞は「重たい」ので、単に取っちゃいました。

2019-04-07 11:15 UTC, tockri commented on _ja/tour/for-comprehensions.md
> +`yield`文と使われるfor`ループ`は実は`List`を生成します。
```suggestion
この`yield`文と一緒に使われている`for`ループは実際には`List`を生成します。
```
この「The」は意味のあるTheですね。

2019-04-07 11:15 UTC, tockri commented on _ja/tour/for-comprehensions.md
> +`yield user.name`と言ったので、それは`List[String]`です。
```suggestion
`yield user.name`を返しているので、型は`List[String]`になります。
```
意訳ですけど、もとの英文もえらい曖昧なので、そのままだとほんとにわからないw

2019-04-07 11:15 UTC, tockri commented on _ja/tour/for-comprehensions.md
> +ここで`n == 10`と`v == 10`の場合、最初のイテレータでは`i == 0`と`j == 0`となり、`i + j != v`となるので、何も得られません。
```suggestion
この例では`n == 10`で`v == 10`です。最初のイテレーションでは`i == 0`かつ`j == 0`で、`i + j != v`となるので、何も生成されません。
```

2019-04-07 11:15 UTC, tockri commented on _ja/tour/for-comprehensions.md
> +`i`が`1`に増加する前に、`j`はあと9回にインクリメントされます。`if`ガードがなければ、単純に以下の内容が表示されます。
```suggestion
`j`があと9回インクリメントされた後、`i`が`1`に増加します。`if`ガードがなければ、単純に以下の内容が表示されます。
```
文中にあるbeforeも、「〜してから」「〜の後で」と訳して前後をひっくり返さないほうが自然になりますねー。基本、前後をひっくり返さないほうが元の文章の意図に沿うことが多いように思います。

2019-04-07 11:15 UTC, tockri commented on _ja/tour/for-comprehensions.md
> +内包表記はリストに制限されまん。
```suggestion
内包表記はリストだけのものではありません。
```
されまんw

2019-04-07 11:15 UTC, tockri commented on _ja/tour/for-comprehensions.md
> +内包表記の中では`yield`を省略することができます。その場合、内包表記は`Unit`を返します。
おお、試してみたらほんとだ。知らなかった…

2019-04-09 04:43 UTC, take2webservice commented on _ja/tour/for-comprehensions.md
> +`yield`文と使われるfor`ループ`は実は`List`を生成します。
ぬー、Theの訳し方が難しい…

2019-04-09 04:49 UTC, take2webservice commented on _ja/tour/for-comprehensions.md
> +`i`が`1`に増加する前に、`j`はあと9回にインクリメントされます。`if`ガードがなければ、単純に以下の内容が表示されます。
文の流れは変えずに、beforeを意訳する…
なかなか難しいですが、スッキリしますねー

2019-04-09 04:50 UTC, merged