Japanese translation of TOUR OF SCALA generic-classes
take2webservice/docs.scala-lang pull request #23
Opened 2019-04-03 14:48 UTC by take2webservice

最後の注意書きにある`true integers`ってどう訳すのが良いんでしょうか？

2019-04-07 12:16 UTC, tockri requested changes
変位指定、いつも<とか>とか+とかわかんなくなるんですよね…

2019-04-07 12:16 UTC, tockri commented on _ja/tour/generic-classes.md
> +ジェネリッククラスは角カッコの中に`[]`パラメータとして型を1つ受け取ります。
```suggestion
ジェネリッククラスは角カッコ`[]`の中にパラメータとして型を1つ受け取ります。
```

2019-04-07 12:16 UTC, tockri commented on _ja/tour/generic-classes.md
> +これは基礎となるリスト`var elements: List[A] = Nil`は型`A`の要素のみを格納できることを意味します。
```suggestion
これはメンバーのリスト`var elements: List[A] = Nil`が型`A`の要素のみを格納できることを意味します。
```
最初「このクラスの本質である」って書いたけど重すぎるのでさらっと。

2019-04-07 12:16 UTC, tockri commented on _ja/tour/generic-classes.md
> +(注意: `elements = x :: elements`は`elements`に`x`を現在の`elements`の先頭に追加した新しいリストを割り当て直します。)。
```suggestion
(注: `elements = x :: elements`は、`x`を現在の`elements`の先頭に追加した新しいリストを`elements`に割り当て直します。)。
```

2019-04-07 12:16 UTC, tockri commented on _ja/tour/generic-classes.md
> +ジェネリッククラスの使うには、`A`代わりに角カッコの中に型を入れます。
```suggestion
ジェネリッククラスを使うには、角カッコの中に`A`の代わりに型を入れます。
```

2019-04-07 12:16 UTC, tockri commented on _ja/tour/generic-classes.md
> +_注意: ジェネリック型のサブタイプは不変です。もし`Stack[Char]`型の文字スタックがあったとしても、それを`Stack[Int]`型の整数スタックとしては使うことができません。文字スタックに真の整数は入力できるので、このことは不合理に聞こえるかもしれません。最後に、`B = A`の場合に限り、`Stack[A]`はただの`Stack[B]`のサブタイプとなります。これは非常に制限的で
```suggestion
_注意: ジェネリック型のサブタイプは不変です。`Stack[Char]`型の文字スタックがあるとき、それを`Stack[Int]`型の整数スタックとしては使うことはできません。文字スタックに整数を入れることはできるので、このことは変に思えるしれません。結論としては、`B = A`の場合に限り、`Stack[A]`は`Stack[B]`の唯一のサブタイプとなります。これでは制限が強いので、ジェネリックタイプのサブタイプの振る舞いをコントロールするために、Scalaは[型引数アノテーションの仕組み](variances.html)を提供します。_
```
real integersにちょうどいい日本語、無いですね…「本物の整数」じゃおかしいもんなー。
ちなみに言ってることはこういうことですね。
```Scala
val list = scala.collection.mutable.MutableList[Char]()
list += 65
list += 66
list += 67
println(list.mkString(",")) // A,B,C
```

2019-04-09 05:12 UTC, take2webservice commented on _ja/tour/generic-classes.md
> +これは基礎となるリスト`var elements: List[A] = Nil`は型`A`の要素のみを格納できることを意味します。
なるほど
「クラスの底に潜む」=> 「クラスの中にある」 => 「メンバー」
みたいな感じになるわけですね

2019-04-09 05:18 UTC, take2webservice commented on _ja/tour/generic-classes.md
> +_注意: ジェネリック型のサブタイプは不変です。もし`Stack[Char]`型の文字スタックがあったとしても、それを`Stack[Int]`型の整数スタックとしては使うことができません。文字スタックに真の整数は入力できるので、このことは不合理に聞こえるかもしれません。最後に、`B = A`の場合に限り、`Stack[A]`はただの`Stack[B]`のサブタイプとなります。これは非常に制限的で
おー、なるほど！
これは分からんっすw

2019-04-09 05:28 UTC, take2webservice commented on _ja/tour/generic-classes.md
> +_注意: ジェネリック型のサブタイプは不変です。もし`Stack[Char]`型の文字スタックがあったとしても、それを`Stack[Int]`型の整数スタックとしては使うことができません。文字スタックに真の整数は入力できるので、このことは不合理に聞こえるかもしれません。最後に、`B = A`の場合に限り、`Stack[A]`はただの`Stack[B]`のサブタイプとなります。これは非常に制限的で
「ASCIIコードとして真の整数は入力できるので、」くらいにしたいですねー

2019-04-09 13:55 UTC, tockri commented on _ja/tour/generic-classes.md
> +_注意: ジェネリック型のサブタイプは不変です。もし`Stack[Char]`型の文字スタックがあったとしても、それを`Stack[Int]`型の整数スタックとしては使うことができません。文字スタックに真の整数は入力できるので、このことは不合理に聞こえるかもしれません。最後に、`B = A`の場合に限り、`Stack[A]`はただの`Stack[B]`のサブタイプとなります。これは非常に制限的で
まあcharに255以下のint代入できるのとか普通だし（ですよね？）、特に訳さなくていいんじゃないですかねー。

2019-04-09 15:31 UTC, take2webservice commented on _ja/tour/generic-classes.md
> +_注意: ジェネリック型のサブタイプは不変です。もし`Stack[Char]`型の文字スタックがあったとしても、それを`Stack[Int]`型の整数スタックとしては使うことができません。文字スタックに真の整数は入力できるので、このことは不合理に聞こえるかもしれません。最後に、`B = A`の場合に限り、`Stack[A]`はただの`Stack[B]`のサブタイプとなります。これは非常に制限的で
なるほど！
いやー、自分が文字コード周りの理解が薄いのが判ったので、お恥ずかしいばかり！
（charほとんど使ったこと無かったっす）

2019-04-09 15:31 UTC, merged