Japanese translation of TOUR OF SCALA upper-type-bounds
take2webservice/docs.scala-lang pull request #24
Opened 2019-04-09 07:52 UTC by take2webservice

2019-04-10 16:59 UTC, tockri requested changes
記号が覚えられないんだよなあ…

2019-04-10 16:59 UTC, tockri commented on _ja/tour/upper-type-bounds.md
> +型境界は具体的な値を制限し、そのような型のメンバーに関するより多くの情報を明らかにするかもしれません。
```suggestion
型境界は型変数に入れられる値を制限して、時にはそれらの型についてより多くの情報を与えます。
```
型変数のconcrete valueというのは、`List[A]`に対して`List[Int]`があるとき、`A`という型変数に具体的な値`Int`を入れているということです。
値＝型なので、ややこしいですね。

2019-04-10 16:59 UTC, tockri commented on _ja/tour/upper-type-bounds.md
> +_上限型境界_ は型変数`T`が型`A`のサブタイプを参照することを宣言します。
```suggestion
_上限型境界_ `T <: A` は型変数`T`が型`A`のサブタイプであることを宣言します。
```

2019-04-14 13:10 UTC, take2webservice commented on _ja/tour/upper-type-bounds.md
> +型境界は具体的な値を制限し、そのような型のメンバーに関するより多くの情報を明らかにするかもしれません。
なるほどなるほど

2019-04-14 13:10 UTC, merged