Japanese translation of TOUR OF SCALA variances
take2webservice/docs.scala-lang pull request #25
Opened 2019-04-09 07:53 UTC by take2webservice

2019-04-10 18:52 UTC, tockri requested changes
この章は訳しにくい構造の文が多かったですねー。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +変位指定は複合型のサブタイプ関係とコンポーネント型のサブタイプ関係の相関です。
```suggestion
変位指定は複合型の間の継承関係とそれらの型パラメータ間の継承関係の相関です。
```
component typesは「含んでいる型」ですね。List[Int]が含んでいる型はIntで、つまり型パラメータ。そう書いとけと原文に言いたい。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +Scalaは型パラメータの[ジェネリッククラス](generic-classes.html)の変位指定アノテーションをサポートしています。
```suggestion
Scalaは[ジェネリッククラス](generic-classes.html)の型パラメータの変位指定アノテーションをサポートしています。
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +そのためアノテーションを使わなかった場合に、共変、反変、または不変を利用することができます。
```suggestion
変位指定アノテーションにより共変、反変にでき、アノテーション無しなら不変になります。
```
嫌な構造の文ですねー。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +その一方で変位指定が無ければ抽象性の再利用が制限されます。
```suggestion
その一方で変位指定が無いと、クラスを抽象化して再利用しにくくなります。
```
英語：複雑な名詞→日本語：動詞に変えて訳すとわかりやすくなる例ですね。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +ジェネリッククラスの型パラメータ`A`はアノテーション`+A`を使うことで共変にすることができます。
```suggestion
ジェネリッククラスの型パラメータ`A`はアノテーション`+A`を使うと共変になります。
```
「こと」を取ると読みやすいって[誰か](https://note.mu/ryopan/n/nc0e43404be55)が言ってた。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +ある`class List[+A]`がある時`A`を共変にすることは、2つの型`A`と`B`に対して`A`が`B`のサブタイプであることをほのめかします。
```suggestion
`class List[+A]`という表記では`A`が共変になり、`A`が`B`のサブタイプであるような`A`と`B`に対して`List[A]`が`List[B]`のサブタイプになることを示します。
```
ここは全部くっつけて多少前後をひっくり返したりしないとわかんなくなる文でした。このwhereは関係代名詞で「two types `A` and `B`」を修飾しているので後ろ→前と訳したほうがスッキリ書けるケースでした。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +その時、`List[A]`は`List[B]`のサブタイプとなります。
```suggestion
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +型パラメータ`A`が共変である場合、Scalaの標準ライブラリはジェネリックイミュータブル`sealed abstract class List[+A]`クラスを持ちます。
```suggestion
Scalaの標準ライブラリにはイミュータブルなジェネリック`sealed abstract class List[+A]`クラスがあり、この型パラメータ`A`は共変です。
```
このwhereは接続詞で、「そこでは」と読めば前→後ろと訳してすんなり通ります。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +直感的に猫のリストと犬のリストはそれれぞれ動物のリストであり、それらを`List[Animal]`で代替できると理解できます。
```suggestion
直感的に猫のリストと犬のリストはそれれぞれ動物のリストであり、それらで`List[Animal]`を代替できると理解できます。
```
おしいw

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +もし`List[A]`が共変でなければ、最後の2つのメソッド呼び出しはコンパイルされず、`printAnimalNames`メソッドの使い勝手はひどく制限されます。
いい感じ。この,whichも前の文全体を修飾するので接続詞と考えて前→後ろと訳せるケースですね。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +型パラメータ`A`のジェネリッククラスはアノテーション`-A`を利用することで、反変にすることができます。
```suggestion
ジェネリッククラスの型パラメータ`A`はアノテーション`-A`を利用することで、反変にすることができます。
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +これはクラスとその型パラメータの間でサブタイプ関係を作ります。
```suggestion
これはクラスとその型パラメータの間でサブタイプ関係を作るところは似ているのですが、得られる結果は共変の反対となります。
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +それは似ていますが、共変で得られるものとは反対のものになります。
```suggestion
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +`class Writer[-A]`がある時、`A`を反変とすると、2つの型`A`と`B`に対し、`A`が`B`のサブタイプの場合、`Writer[B]`は`Writer[A]`のサブタイプであることを匂わせます。
```suggestion
`class Writer[-A]`という表記では`A`は反変となり、`A`が`B`のサブタイプであるような`A`と`B`に対し、`Writer[B]`は`Writer[A]`のサブタイプであることを示します。
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +そのため`Printer[Animal]`を`Printer[Cat]`代わりに使い、`Printer[A]`を反変にすることができます。
```suggestion
したがって、必要であれば`Printer[Animal]`を`Printer[Cat]`の代わりに使えるべきです。`Printer[A]`を反変にすると、まさにそういうことができるようになります。
```
if we wishのつく場所が最初わからなかった。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +Scalaのジェネリッククラスは標準では不変です。
```suggestion
Scalaのジェネリッククラスはデフォルトでは不変です。
```
変位指定するのも標準のうちなので。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +以下の例の状況では、`Container`クラスは不変です。`Container[Cat]`は`Container[Animal]`_ではなく_、逆もまた真ではありません。
```suggestion
以下の例の状況では、`Container`クラスは不変です。`Container[Cat]`は`Container[Animal]`_ではなく_、逆も同様です。
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +`Container[Cat]`が `Container[Animal]`でもあることはは当然かもしれませんが、ミュータブルジェネリッククラスが共変であることを許すことは安全ではありません。
```suggestion
`Container[Cat]`が `Container[Animal]`でもあることはは自然なように思えるかもしれませんが、ミュータブルなジェネリッククラスを共変にするのは安全ではありません。
```
「こと」を取ると…

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +このようなことが起こりえます。
```suggestion
この例では、 `Container` が不変であるのはとても重要です。もし `Container` が共変だと、このようなことが起こりえます。
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +`Function1`はその引数の型を通して反変であり、戻り値の型を通して共変です。
```suggestion
`Function1`はその引数の型に対して反変であり、戻り値の型に対して共変です。
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +先ほど利用されたものと同様に`Cat`, `Dog`, `Animal`の継承ツリーは以下のものを考えてください。
```suggestion
先ほど利用された`Cat`, `Dog`, `Animal`の継承ツリーに、以下のものを加えましょう：
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +動物の種類を受け取り、それらが食べる食料の種類を返す関数を使うとした場合。
```suggestion
動物の種類を受け取り、それらが食べる食料の種類を返す関数について考えましょう。
```
supposeはthinkに変えても意味が通じます。

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +例えば、クラスの抽象化が定義(declaration-site variance)された時にアノテーションが追加されるという点で、Scalaの変位指定アノテーションはC#のそれと非常に似ています。
```suggestion
例えば、Scalaの変位指定アノテーションはC#のそれと非常に似ています。C#ではクラスの抽象性を定義する時にアノテーションが追加されます。(宣言時の変位指定)
```

2019-04-10 18:52 UTC, tockri commented on _ja/tour/variances.md
> +しかしながら、Javaでは、クラスの抽象化が使われた時(use-site variance)に変位指定アノテーションはクライアントにより与えられます。
```suggestion
しかしながら、Javaでは、クラスの抽象性を使う時に変位指定アノテーションが利用側のコードから与えられます。(使用時の変位指定)
```
へえー、Javaだとこんなのあるんだ知らなかった
`List<? extends Dog>`ってやると共変な`List<Dog>`ができるんですねー。確かに利用時定義だ。

2019-04-11 05:41 UTC, take2webservice commented on _ja/tour/variances.md
> +変位指定は複合型のサブタイプ関係とコンポーネント型のサブタイプ関係の相関です。
おー、なるほど！コンポーネント型ってなんだよってなってました！

2019-04-11 05:45 UTC, take2webservice commented on _ja/tour/variances.md
> +そのためアノテーションを使わなかった場合に、共変、反変、または不変を利用することができます。
あー、`if no annotations are used`がかかるの`invariant `だけなんですね！
訳してて、全然アノテーション使ってるやんけ！？他に@から始まるアノテーション的なのがあるのかなーってなってました！

2019-04-11 05:47 UTC, take2webservice commented on _ja/tour/variances.md
> +その一方で変位指定が無ければ抽象性の再利用が制限されます。
なるほどなるほど

2019-04-11 05:52 UTC, take2webservice commented on _ja/tour/variances.md
> +ジェネリッククラスの型パラメータ`A`はアノテーション`+A`を使うことで共変にすることができます。
なるほどなるほど
断定っぽい感じにすれば良くなりそうです！

2019-04-11 05:56 UTC, take2webservice commented on _ja/tour/variances.md
> +例えば、クラスの抽象化が定義(declaration-site variance)された時にアノテーションが追加されるという点で、Scalaの変位指定アノテーションはC#のそれと非常に似ています。
やっぱり文章を分けた方が良かったorz

2019-04-11 06:01 UTC, take2webservice commented on _ja/tour/variances.md
> +しかしながら、Javaでは、クラスの抽象化が使われた時(use-site variance)に変位指定アノテーションはクライアントにより与えられます。
`use-site`で使用時って訳せるんですねー

あと`client`も利用者でOKと

Javaでそういう書き方ができるの僕も知りませんでしたー

（というか変位指定は意識して自分で書いたことが無いですね）

2019-04-11 06:04 UTC, merged