Japanese translation of TOUR OF SCALA lower-type-bounds
take2webservice/docs.scala-lang pull request #26
Opened 2019-04-09 11:01 UTC by take2webservice

2019-04-13 05:19 UTC, tockri requested changes
最後のトリックは実際のコードではやってはならぬやつですね。

2019-04-13 05:19 UTC, tockri commented on _ja/tour/lower-type-bounds.md
> + [上限型境界](upper-type-bounds.html) が型を別の型のサブタイプに制限する一方で、*下限型境界*は型が別の型のスーパータイプになるよう宣言します。表現`B >: A`はパラメータ`B`または抽象型`B`が型`A`のスーパータイプを指すことを表します。ほとんどのケースで`A`はそのクラスの型パラメータであり、`B`はメソッドの型パラメータになります。
```suggestion
 [上限型境界](upper-type-bounds.html) が型を別の型のサブタイプに制限する一方で、*下限型境界*は型が別の型のスーパータイプになるよう宣言します。表現`B >: A`はパラメータ`B`または抽象型`B`が型`A`のスーパータイプであることを表します。ほとんどのケースで`A`はそのクラスの型パラメータであり、`B`はメソッドの型パラメータになります。
```

2019-04-13 05:19 UTC, tockri commented on _ja/tour/lower-type-bounds.md
> +`class ListNode`は型`B` (`head`)の要素を含むノードであり、リストの残りの部分(`tail`)への参照です。
```suggestion
`class ListNode`は型`B` (`head`)の要素と、リストの残りの部分(`tail`)への参照を持つノードです。
```

2019-04-13 05:19 UTC, tockri commented on _ja/tour/lower-type-bounds.md
> +`class Node`とそのスーパータイプは共変であるので、`+B`としています。
```suggestion
`class Node`とそのサブタイプは、`+B`とあるので、共変です。
```
becauseは前後をひっくり返さなくてすむ日本語がないんですよねー

2019-04-13 05:19 UTC, tockri commented on _ja/tour/lower-type-bounds.md
> +しかしながら、このプログラムはコンパイル _されません_。`prepend`の中のパラメータ`elem`が *共* 変と宣言した型`B`だからです。
```suggestion
しかしながら、このプログラムはコンパイル _されません_。`prepend`のパラメータ`elem`が、宣言時に*共* 変と宣言した型`B`になっているからです。
```

2019-04-13 05:19 UTC, tockri commented on _ja/tour/lower-type-bounds.md
> +これは動きません、なぜなら関数はそれらの型パラメータの中では*反*変であり、それらの結果型の中では*共*変だからです。
```suggestion
なぜ通らないかというと、関数はそれらの型パラメータの中では*反*変であり、それらの結果型の中では*共*変だからです。
```
ためしにコンパイルしてみたらこんなエラーでした。ほんとだ、「反変の位置で共変の型がある」と言ってる。
```
Error:(2, 21) covariant type B occurs in contravariant position in type B of value elem
def prepend(elem: B): Node[B]
```

2019-04-13 05:19 UTC, tockri commented on _ja/tour/lower-type-bounds.md
> +これを解決するためには、`prepend`の中でパラメータ`elem`の型の変位指定を弾く必要があります。
```suggestion
これを解決するためには、`prepend`のパラメータ`elem`の型の変位指定を逆転させる必要があります。
```

2019-04-13 05:19 UTC, tockri commented on _ja/tour/lower-type-bounds.md
> +今、以下のようなことができます。
```suggestion
すると、以下のようなことができます。
```

2019-04-13 05:19 UTC, tockri commented on _ja/tour/lower-type-bounds.md
> +`Node[Bird]`は`africanSwallowList`アサインできますが、その際`EuropeanSwallow`を受け取ります。
```suggestion
`Node[Bird]`は`africanSwallowList`をアサインできますが、その後`EuropeanSwallow`を受け入れられます。
```

2019-04-14 13:21 UTC, take2webservice commented on _ja/tour/lower-type-bounds.md
> +`class ListNode`は型`B` (`head`)の要素を含むノードであり、リストの残りの部分(`tail`)への参照です。
見返してみると、「であり」はおかしい orz

2019-04-14 13:29 UTC, take2webservice commented on _ja/tour/lower-type-bounds.md
> +これを解決するためには、`prepend`の中でパラメータ`elem`の型の変位指定を弾く必要があります。
なるほど！

flipで弾くって意味わからんなと思っていたら、「逆転」と訳せば良かったんですね！

2019-04-14 13:30 UTC, take2webservice commented on _ja/tour/lower-type-bounds.md
> +`Node[Bird]`は`africanSwallowList`アサインできますが、その際`EuropeanSwallow`を受け取ります。
あー、ここは受動態じゃないから`Node[Bird]`が受け取るになるんですね。
勢いでごまかしてました。

2019-04-14 13:31 UTC, merged