Japanese translation of TOUR OF SCALA abstract-type-members
take2webservice/docs.scala-lang pull request #27
Opened 2019-04-09 18:44 UTC by take2webservice

2019-04-14 14:14 UTC, tockri requested changes
知識としては知ってるけど自分で使えないやつだ…

2019-04-14 14:14 UTC, tockri commented on _ja/tour/abstract-type-members.md
> +トレイトと抽象クラスのような抽象型は順番に抽象型メンバーを持つことができます。
```suggestion
トレイトや抽象クラスのような抽象型は抽象型メンバーを持つことができます。
```
in turnはトレイとと抽象クラスのどちらも、と言いたいんだと思いますが、無くしちゃうのが一番スムーズですね。

2019-04-14 14:14 UTC, tockri commented on _ja/tour/abstract-type-members.md
> +これは具体的な実装が明確に型を定義することを意味します。
```suggestion
これは具体的な実装で実際の型を定義するという意味です。
```
「こと」をなくすと読みやすく・・・

2019-04-14 14:14 UTC, tockri commented on _ja/tour/abstract-type-members.md
> +こちらが例になります。
```suggestion
こちらが例です。
```
コンビニ敬語警察だ！🚓

2019-04-14 14:14 UTC, tockri commented on _ja/tour/abstract-type-members.md
> +`T`の上限型境界の仕様において、更に別の抽象型`U`の使い方に気をつけてください。
```suggestion
`T`の上限型境界の定義に出てきた、更に別の抽象型`U`の使い方に気をつけてください。
```
specification = definitionでよさそう。

2019-04-14 14:14 UTC, tockri commented on _ja/tour/abstract-type-members.md
> +この`class SeqBuffer`はバッファーの中のシーケンスのみを保存することができます。それは新しい抽象型`U`により型`T`は`Seq[U]`のサブタイプである必要があることを明言しているからです。
```suggestion
この`class SeqBuffer`はこのバッファーの中にシーケンスのみを保持することができます。それは型`T`は新しい抽象型`U`を使った`Seq[U]`のサブタイプである必要があると明示しているからです。
```

2019-04-14 14:14 UTC, tockri commented on _ja/tour/abstract-type-members.md
> +こちらでは抽象型`T`を具体的な型`List[Int]`に設定するために、ファクトリー`newIntSeqBuf`は`IntSeqBuf`(つまり`new IntSeqBuffer`)の無名クラスの実装を使います。
```suggestion
ここで、ファクトリー`newIntSeqBuf`は抽象型`T`を具体的な型`List[Int]`に設定するために、`IntSeqBuf`(つまり`new IntSeqBuffer`)を無名クラスで実装します。
```

2019-04-14 14:14 UTC, tockri commented on _ja/tour/abstract-type-members.md
> +これにより抽象型メンバーをクラスの型パラメータに変換したり、その逆も可能となります。以下は上記コードの型パラメータのみを使うバージョンです。
```suggestion
抽象型メンバーをクラスの型パラメータに変えることも、その逆も可能です。以下は上記コードの型パラメータのみを使うバージョンです。
```

2019-04-14 14:14 UTC, tockri commented on _ja/tour/abstract-type-members.md
> +ここでは(`+T <: Seq[U]`)をメソッド`newIntSeqBuf`から戻されるオブジェクトの具体的なシーケンス実装の型を隠すために [変位指定アノテーション](variances.html)を使わなければなりません。さらに、抽象型メンバをパラメータで置換することができないケースがあります。
👏👏👏

2019-04-23 16:49 UTC, take2webservice commented on _ja/tour/abstract-type-members.md
> +トレイトと抽象クラスのような抽象型は順番に抽象型メンバーを持つことができます。
なるほどなるほど

2019-04-23 16:50 UTC, take2webservice commented on _ja/tour/abstract-type-members.md
> +これは具体的な実装が明確に型を定義することを意味します。
「こと」無くすのに慣れず… orz

2019-04-23 16:57 UTC, merged