Japanese translation of TOUR OF SCALA inner-classes
take2webservice/docs.scala-lang pull request #28
Opened 2019-04-09 18:45 UTC by take2webservice

2019-04-14 16:24 UTC, tockri requested changes
うええ、なんだこれGraph#Nodeなんて初めて知った。こういうことしたい場合は
```
object Graph {
   class Node {}
}
```
ってやるもんだと思ってた。

2019-04-14 16:24 UTC, tockri commented on _ja/tour/inner-classes.md
> +Javaのような言語とは対照的に、内部クラスは外側のクラスのメンバーとなる場合、Scalaではそのような内部クラスは外側のオブジェクトに束縛されます。
```suggestion
Javaのような、内部クラスが外側のクラスのメンバーとなる言語とは対照的に、Scalaでは、そのような内部クラスは外側のオブジェクトに束縛されます。
```

2019-04-14 16:24 UTC, tockri commented on _ja/tour/inner-classes.md
> +コンパイルの際、コンパイラにどのノードがなんのグラフに属しているのか混同することを防いでほしいのです。
```suggestion
どのノードがなんのグラフに属しているのかを私達が混同しないように、コンパイラがコンパイル時に防いでほしいのです。
```

2019-04-14 16:24 UTC, tockri commented on _ja/tour/inner-classes.md
> +その違いを図示するために、グラフデータ型の実装をさっと書きます。
```suggestion
その違いを示すために、グラフデータ型の実装をさっと書きます。
```
図示してねえw

2019-04-14 16:24 UTC, tockri commented on _ja/tour/inner-classes.md
> +`node1`、`node2`、そして `node3`の型が`graph1.Node`であることを明確にするために、明示的に宣言しています。
```suggestion
わかりやすくするため`node1`、`node2`、`node3`の型を`graph1.Node`と明示的に宣言しましたが、なくてもコンパイラは推論できます。
```
唐突な could have は仮定法過去ってやつですね。if条件が省略されてる。

2019-04-14 16:24 UTC, tockri commented on _ja/tour/inner-classes.md
> +これは`graph1.newNode`を呼び出す時、`new Node`を呼び出し、そのメソッドがインスタンス`graph1`特有の`Node`のインスタンスを使用しているからです。
```suggestion
これは`new Node`を呼んでいる`graph1.newNode`を呼び出す時、そのメソッドが`Node`のインスタンス`graph1`を使用しているからです。
```

2019-04-14 16:24 UTC, tockri commented on _ja/tour/inner-classes.md
> +今2つのグラフがあれば、Scalaの型システムは1つのグラフの中でノードと別のグラフのノードを混ぜることを許しません。
```suggestion
2つのグラフがあるとき、Scalaの型システムは1つのグラフの中で定義されたノードと別のグラフで定義されたノードを混ぜることを許しません。
```

2019-04-14 16:24 UTC, tockri commented on _ja/tour/inner-classes.md
> +それは他のグラフのノードは別の型だからです。
```suggestion
それは別のグラフのノードは別の型を持つからです。
```

2019-04-23 16:59 UTC, take2webservice commented on _ja/tour/inner-classes.md
> +Javaのような言語とは対照的に、内部クラスは外側のクラスのメンバーとなる場合、Scalaではそのような内部クラスは外側のオブジェクトに束縛されます。
あー、掛かり方が完全に逆 orz

2019-04-23 17:02 UTC, take2webservice commented on _ja/tour/inner-classes.md
> +その違いを図示するために、グラフデータ型の実装をさっと書きます。
図示してないっすねw

2019-04-23 17:05 UTC, take2webservice commented on _ja/tour/inner-classes.md
> +`node1`、`node2`、そして `node3`の型が`graph1.Node`であることを明確にするために、明示的に宣言しています。
14年ぶりくらいに仮定法過去の存在を思い出しました。
なるほどif省略できるんですね。

2019-04-23 17:06 UTC, take2webservice commented on _ja/tour/inner-classes.md
> +これは`graph1.newNode`を呼び出す時、`new Node`を呼び出し、そのメソッドがインスタンス`graph1`特有の`Node`のインスタンスを使用しているからです。
わかりやすいっす！

2019-04-23 17:11 UTC, merged