Japanese translation of TOUR OF SCALA compound-types
take2webservice/docs.scala-lang pull request #29
Opened 2019-04-09 19:12 UTC by take2webservice

2019-04-14 17:26 UTC, tockri requested changes
細別（って日本語を当てるって初めて知った）はめったに使わないですね。型に名前があるってことが重要なので、無名型みたいなのはちょっと。TypeScriptではめちゃ使うけどあれはもっともっと限定できるから。

2019-04-14 17:26 UTC, tockri commented on _ja/tour/compound-types.md
> +オブジェクトの型がいくつかの他の型のサブタイプであることを表現する必要がある時があります。
```suggestion
オブジェクトの型が複数の他の型のサブタイプであることを表現する必要がある時があります。
```
ひらがなの言葉より漢字の言葉のほうが意味が強く感じられるので、この文でいちばん強調したい単語「several」を漢字にしてみました

2019-04-14 17:26 UTC, tockri commented on _ja/tour/compound-types.md
> +Scalaでは*複合型*の助けにより表現することができます。それはオブジェクト型の交点です。
```suggestion
Scalaでは*複合型*の助けにより表現できます。複合型とはオブジェクトの型同士を重ねることです。
```

2019-04-14 17:26 UTC, tockri commented on _ja/tour/compound-types.md
> +2つのトレイト`Cloneable`と`Resetable`があると考えてください。
```suggestion
2つのトレイト`Cloneable`と`Resetable`があるとしましょう。
```

2019-04-14 17:26 UTC, tockri commented on _ja/tour/compound-types.md
> +今、関数`cloneAndReset`を書きたいとします。それはオブジェクトを受け取り、それをクローンしオリジナルのオブジェクトをリセットします。
```suggestion
今、関数`cloneAndReset`を書きたいとします。それはオブジェクトを受け取り、それをクローンして、元のオブジェクトをリセットします。
```

2019-04-14 17:26 UTC, tockri commented on _ja/tour/compound-types.md
> +パラメータ`obj`の型は何かという疑問が上がります。もし`Cloneable`であれば、オブジェクトを`clone`することができますが、`reset`することはできません。もし`Resetable`であれば、`reset`することができますが、`clone`の操作はできません。そのような状態で型キャストを回避するために`obj`の型を`Cloneable`と`Resetable`の両方である
```suggestion
パラメータ`obj`の型は何かという疑問が上がります。もし`Cloneable`であれば、オブジェクトを`clone`することができますが、`reset`することはできません。もし`Resetable`であれば、`reset`することができますが、`clone`の操作はできません。そのような状態で型キャストを回避するために`obj`の型を`Cloneable`と`Resetable`の両方であると指定することができます。Scalaではこの複合型は`Cloneable with Resetable`のように書くことができます。
```

2019-04-14 17:26 UTC, tockri commented on _ja/tour/compound-types.md
> +複合型はいくつかのオブジェクトから成り、それらは既存のオブジェクトメンバーの署名を絞り込むための一つの改良点です。
```suggestion
複合型は複数のオブジェクトの型からなり、一つだけの細別型(refinement)を持てます。細別型は既存オブジェクトのメンバーのシグネチャを絞り込むのに使えます。
```
[Scala tour日本語訳の先行者さん](https://sites.google.com/site/scalajp/home/documentation/scala_walk_around/compound_types)が「細別」って訳してたのでぐぐったらEffective Scalaでも採用してるみたいなので、細別でいいのかなーと思います。
コード的にはこういうふうに書けるってやつですね。
```
def cloneAndReset(obj: Cloneable{def reset:Unit}): Cloneable
```

2019-04-14 17:26 UTC, tockri commented on _ja/tour/compound-types.md
> +改良点の使い方の例は[ミックスインを用いたクラス合成](mixin-class-composition.html)のページにあります。
```suggestion
細別の使い方の例は[ミックスインを用いたクラス合成](mixin-class-composition.html)のページにあります。
```
っていいつつ、[mixin-class-composition.html](https://docs.scala-lang.org/tour/mixin-class-composition.html)に無いんだよなあ……ひどいなあ……

2019-04-23 17:13 UTC, take2webservice commented on _ja/tour/compound-types.md
> +Scalaでは*複合型*の助けにより表現することができます。それはオブジェクト型の交点です。
「型同士を重ねる」って訳せば良かったんですね。

交点ってなんだってなってましたw

2019-04-23 17:17 UTC, take2webservice commented on _ja/tour/compound-types.md
> +複合型はいくつかのオブジェクトから成り、それらは既存のオブジェクトメンバーの署名を絞り込むための一つの改良点です。
Effective Scalaドキュメントで存在してたんですね。

あとでしっかり読んでみます！

2019-04-23 17:18 UTC, merged