Japanese translation of TOUR OF SCALA implicit-parameters
take2webservice/docs.scala-lang pull request #31
Opened 2019-04-10 09:39 UTC by take2webservice

2019-04-17 15:33 UTC, tockri requested changes
悪名高いimplicit parameterですねー。でも便利なんだよなー。でも読めなくなるんだよなー。

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +* Scalaは暗黙のパラメータブロックを持つメソッドが呼び出された時点で、まず(プレフィックスなしに)に直接アクセスできる暗黙の定義と暗黙のパラメータを探します。
```suggestion
* Scalaは暗黙のパラメータブロックを持つメソッドが呼び出されている箇所で、直接(プレフィックスなしに)アクセスできる暗黙の定義と暗黙のパラメータをまず最初に探します。
```

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +* そして全てのコンパニオンオブジェクトの中でimplicitで印をつけられ、暗黙に候補となる型と関連づけられたメンバーを探します。
```suggestion
* 次に、候補となる型に関連づけられた全てのコンパニオンオブジェクトの中でimplicitと宣言されているメンバーを探します。
```

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +より詳しいScalaがimplicitを探すガイドは[FAQ](//docs.scala-lang.org/tutorials/FAQ/finding-implicits.html)で見ることができます。
```suggestion
Scalaがimplicitをどこから見つけるかについてのより詳しいガイドは[FAQ](//docs.scala-lang.org/tutorials/FAQ/finding-implicits.html)で見ることができます。
```

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +以下の例では、モノイドの`add`と`unit`の演算を使い、要素のリストの合計を計算するメソッド`sum`を定義しています。
```suggestion
以下の例では、モノイドの`add`と`unit`の演算を使い、要素のリストの合計を計算するメソッド`sum`を定義しています。
implicitの値がトップレベルでないことに注意してください。
```

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +`モノイド`はここでは`add`と呼ばれる演算子を定義します。演算子は`A`のペアを組み合わせ、別の`A`を返します。そしてそれは(特別な)`A`を作ることができる`unit`と呼ばれる演算子です。
```suggestion
`モノイド`はここでは`add`と呼ばれる処理を定義します。この処理は`A`のペアを結合して、別の`A`を返します。また、(特定の)`A`を作ることができる`unit`と呼ばれる処理も定義します。
```

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +どのように暗黙のパラメータが動くかを見るには、まずは文字列と整数のためにそれぞれモノイド`stringMonoid`と`intMonoid`を定義します。`implicit`キーワードは対応するオブジェクトは暗黙に使われうることを指し示します。
```suggestion
どのように暗黙のパラメータが働くかを示すために、まずは文字列と整数のためのモノイド`stringMonoid`と`intMonoid`を定義します。`implicit`キーワードは対応するオブジェクトが暗黙に使われうることを示します。
```

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +メソッド`sum`は`List[A]`を受け取り、`A`を返します。そしてメソッドは初期値`A`を`unit`から受け取り、リスト中でそれぞれ次の`A`を`add`メソッドで組み合わせます。ここでパラメータ`m`をimplicitにすることは、そのメソッドを呼び出すとき、暗黙のパラメータ`m`を使うためにScalaが暗黙の`Monoid[A]`を見つけることができるなら`xs`パラメータを提供す
```suggestion
メソッド`sum`は`List[A]`を受け取り、`A`を返します。このメソッドは初期値`A`を`unit`から受け取り、リスト中の`A`を順番に`add`メソッドで結合します。ここでパラメータ`m`をimplicitにしているのは、そのメソッドを呼び出すとき、Scalaが暗黙のパラメータ`m`として暗黙の`Monoid[A]`を見つけることができるなら、私達は`xs`パラメータを提供するだけで良いということです。
```
なっがいなこの文w

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +`main`メソッドにて`sum`を2回呼び出すと、`xs`パラメータだけが提供されます。そうなるとScalaは先に言及したスコープの中でimplicitを探します。最初の`sum`の呼び出しは`List[Int]`を`xs`を渡します。それは `A`が`Int`であることを意味します。`m`と暗黙のパラメータリストは省略しており、Scalaは`Monoid[Int]`型のimplictを探しま
```suggestion
`main`メソッドでは`sum`を2回呼んでいて、`xs`パラメータだけを与えています。するとScalaは先に言及したスコープの中でimplicitを探します。最初の`sum`の呼び出しは`xs`として`List[Int]`を渡します。それは `A`が`Int`であることを意味します。暗黙のパラメータリスト`m`が省略されているので、Scalaは暗黙の`Monoid[Int]`を探します。最初の探索ルールはこうでした。
```
短く、短く・・・・

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +> Scalaは暗黙のパラメータブロックを持つメソッドが呼び出された時点で、まず(プレフィックスなしに)に直接アクセスできる暗黙の定義と暗黙のパラメータを探します。
```suggestion
> Scalaは暗黙のパラメータブロックを持つメソッドが呼び出されている箇所で、直接(プレフィックスなしに)アクセスできる暗黙の定義と暗黙のパラメータをまず最初に探します。
```

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +`intMonoid`は`main`の中で直接アクセスされる暗黙の定義です。それ正しい型であり、`sum`メソッドに自動的に渡されます。
```suggestion
`intMonoid`は`main`の中で直接アクセスできる暗黙の定義です。型も一致しているので、`sum`メソッドに自動的に渡されます。
```

2019-04-17 15:33 UTC, tockri commented on _ja/tour/implicit-parameters.md
> +`sum`の2回目の呼び出しは`List[String]`を渡します。それは`A`は`String`であることを意味します。暗黙のルックアップは`Int`の時と同様に動きますが、この時は `stringMonoid`を見つけ、`m`として自動的に渡します。
```suggestion
`sum`の2回目の呼び出しは`List[String]`を渡します。それは`A`は`String`であることを意味します。暗黙の値の探索は`Int`の時と同様に動きますが、今回は `stringMonoid`を見つけ、`m`として自動的に渡します。
```

2019-04-23 17:29 UTC, take2webservice commented on _ja/tour/implicit-parameters.md
> +以下の例では、モノイドの`add`と`unit`の演算を使い、要素のリストの合計を計算するメソッド`sum`を定義しています。
訳漏れの補足ありがとうございます！

2019-04-23 17:35 UTC, take2webservice commented on _ja/tour/implicit-parameters.md
> +`main`メソッドにて`sum`を2回呼び出すと、`xs`パラメータだけが提供されます。そうなるとScalaは先に言及したスコープの中でimplicitを探します。最初の`sum`の呼び出しは`List[Int]`を`xs`を渡します。それは `A`が`Int`であることを意味します。`m`と暗黙のパラメータリストは省略しており、Scalaは`Monoid[Int]`型のimplictを探しま
implictの訳し方が判らないっす…

implicitのままでOKな場合と暗黙な場合があって…

2019-04-23 17:38 UTC, merged