Japanese translation of TOUR OF SCALA implicit-conversions
take2webservice/docs.scala-lang pull request #32
Opened 2019-04-11 07:53 UTC by take2webservice

ぬー、意味が全然わからないっす

2019-04-21 01:24 UTC, tockri requested changes
日が開いてしまってすみません。今日のぶん、できました。

2019-04-21 01:24 UTC, tockri commented on _ja/tour/implicit-conversions.md
> +型`S`から型`T`への暗黙の変換はimplicitな値や、implicitなメソッドにより定義されます。
```suggestion
型`S`から型`T`への暗黙の変換は`S => T`という型のimplicit値や、その型に一致するimplicitメソッドで定義されます。
```

2019-04-21 01:24 UTC, tockri commented on _ja/tour/implicit-conversions.md
> +implicitな値は`S => T`な関数を持ち、implicitなメソッドはその型の値に変換できます。
```suggestion

```

2019-04-21 01:24 UTC, tockri commented on _ja/tour/implicit-conversions.md
> +* 型`S`の`e`が持つセレクション`e.m`において、セレクター`m`が`S`のメンバーではない場合
```suggestion
* 型`S`の`e`を使う表記`e.m`があって、セレクター`m`が`S`のメンバーではない場合
```

2019-04-21 01:24 UTC, tockri commented on _ja/tour/implicit-conversions.md
> +最初のケースでは変換`c`を検索します。`c`は`e`に適用可能で、その結果の型が`T`に準拠します。
```suggestion
最初のケースでは、`e`を渡せて、戻り値の型が`T`に適合するような変換`c`を検索します。
```
ここは関係代名詞なんでちゃんと`c`を修飾する感じで訳したほうが通りますね。

2019-04-21 01:24 UTC, tockri commented on _ja/tour/implicit-conversions.md
> +* もし式`e`が型`S`であり、`S`は式の期待する型`T`に準拠しない場合
```suggestion
* もし式`e`が型`S`であり、`S`は式の期待する型`T`に適合しない場合
```

2019-04-21 01:24 UTC, tockri commented on _ja/tour/implicit-conversions.md
> +2つ目のケースでは変換`c`は検索します。`c`は`e`に適用可能で、その結果は`m`と名付けられたメンバー含みます。
```suggestion
2つ目のケースでは、`e`を渡せて、戻り値が`m`というメンバーを持つような変換`c`を検索します。
```

2019-04-21 01:24 UTC, tockri commented on _ja/tour/implicit-conversions.md
> +implicitなメソッド`List[A] => Ordered[List[A]]`がスコープの中にあれば、implicitなメソッド`Int => Ordered[Int]`と同様に、`List[Int]`型の2つのリストにおける以下の処理は正当なものになります。
```suggestion
implicitなメソッド`List[A] => Ordered[List[A]]`と`Int => Ordered[Int]`がスコープの中にあれば、`List[Int]`型の2つのリストにおける以下の処理は正当なものになります。
```
as well as は単に and の代わりである場合があります。

2019-04-21 01:24 UTC, tockri commented on _ja/tour/implicit-conversions.md
> +implicitなインポートされたオブジェクト`scala.Predef`は度々使われる型(例えば`scala.collection.immutable.Map`は`Map`と別名づけられます)とメソッド（例えば`assert`）にいくつかの別名を宣言しますが、暗黙のうちにいくつかの変換もします。
```suggestion
暗黙にインポートされているオブジェクト`scala.Predef`は頻繁に使われる型（例えば`scala.collection.immutable.Map`は`Map`と別名づけられます）とメソッド（例えば`assert`）といくつかの暗黙の型変換を宣言しています。
```
but also = and ですね。

2019-04-21 01:24 UTC, tockri commented on _ja/tour/implicit-conversions.md
> +例えば、`java.lang.Integer`を期待してJavaのメソッドを呼び出す時、自由に`scala.Int`を代わりに渡すことができます。それはPredefオブジェクトが以下の暗黙の変換をを含んでいるからです。
```suggestion
例えば、`java.lang.Integer`を受け取るようなJavaのメソッドを呼び出す時、自由に`scala.Int`を代わりに渡すことができます。それはPredefオブジェクトが以下の暗黙の変換をを含んでいるからです。
```

2019-04-21 01:24 UTC, tockri commented on _ja/tour/implicit-conversions.md
> +暗黙の変換は落とし穴になり得るため、無差別に使えば、暗黙の変換の定義をコンパイルしている時にコンパイラは警告を出します。
```suggestion
暗黙の変換は無差別に使うと落とし穴になり得るため、暗黙の変換の定義をコンパイルしている時にコンパイラは警告を出します。
```
ん？implicit conversionの宣言で警告なんかでないよな…？と思ったけど、でてた。

2019-04-23 17:46 UTC, take2webservice commented on _ja/tour/implicit-conversions.md
> +最初のケースでは変換`c`を検索します。`c`は`e`に適用可能で、その結果の型が`T`に準拠します。
なるほど！

2019-04-23 17:49 UTC, take2webservice commented on _ja/tour/implicit-conversions.md
> +implicitなメソッド`List[A] => Ordered[List[A]]`がスコープの中にあれば、implicitなメソッド`Int => Ordered[Int]`と同様に、`List[Int]`型の2つのリストにおける以下の処理は正当なものになります。
知らなかった…

2019-04-23 17:53 UTC, merged