Japanese translation of TOUR OF SCALA polymorphic-methods
take2webservice/docs.scala-lang pull request #33
Opened 2019-04-11 08:26 UTC by take2webservice

これはいい感じに訳せた気がします

2019-04-21 12:16 UTC, tockri requested changes
変位指定とかより易しい内容なので、文もあんまり入り組んでないですね。

2019-04-21 12:16 UTC, tockri commented on _ja/tour/polymorphic-methods.md
> +Scalaのメソッドは値と同様に型によってパラメータ化することができます。構文はジェネリッククラスの構文と同じです。
```suggestion
Scalaのメソッドは値と同様に型によってパラメータ化することができます。構文はジェネリッククラスの構文と似ています。
```
同じじゃないw

2019-04-21 12:16 UTC, tockri commented on _ja/tour/polymorphic-methods.md
> +型パラメータは角カッコで囲まれますが、値パラメータは丸括弧で囲まれます。
```suggestion
値パラメータは丸括弧で囲まれるのに対して、型パラメータは角カッコで囲まれます。
```

2019-04-21 12:16 UTC, tockri commented on _ja/tour/polymorphic-methods.md
> +こちらが例になります。
```suggestion
こちらが例です。
```
コンビニ敬語警察だ！🚓

2019-04-21 12:16 UTC, tockri commented on _ja/tour/polymorphic-methods.md
> +メソッド`listOfDuplicates`は型パラメータ`A`と値パラメータ`x`と`length`を受け取ります。値`x`は型`A`となります。もし`length < 1`なら空のリストを返します。一方で`x`を再帰呼び出しで返された複写リストの先頭に追加します。(`::`は右側のリストの先頭への左側の要素の追加を意味します。)
```suggestion
メソッド`listOfDuplicates`は型パラメータ`A`と値パラメータ`x`と`length`を受け取ります。値`x`の型は`A`です。もし`length < 1`なら空のリストを返します。それ以外の場合は`x`を再帰呼び出しで返された複写リストの先頭に追加します。(`::`の意味は、左辺の要素を右辺のリストの先頭に追加することです。)
```
ここはleftとrightっていう一般名詞しかない英語より、右辺と左辺というテクニカルタームがちゃんとある日本語のほうが優れてるとこですね！

2019-04-21 12:16 UTC, tockri commented on _ja/tour/polymorphic-methods.md
> +最初の呼び出し例のでは、`[Int]`と書いて明示的に型引数を渡しています。そのため最初の引数は`[Int]`でなければならず、戻される型は`List[Int]`となります。
```suggestion
最初の呼び出し例では、`[Int]`と書いて明示的に型引数を渡しています。そのため最初の引数は`Int`でなければならず、戻される型は`List[Int]`となります。
```

2019-04-21 12:16 UTC, tockri commented on _ja/tour/polymorphic-methods.md
> +2つ目の呼び出し例では必ずしも明示的に型パラメータを渡す必要がないことが判ります。コンパイラはしばしばコンテキストか値引数の型に基づき、型パラメータを推論できます。この例では`"La"`は`String`であり、コンパイラは`A`が`String`でなければならないと気づきます。
```suggestion
2つ目の呼び出し例では必ずしも明示的に型パラメータを渡す必要がないことを示しています。コンパイラは文脈または値引数の型に基づき、型パラメータを推論できることが多いです。この例では`"La"`が`String`なので、コンパイラは`A`が`String`にちがいないことがわかります。
```

2019-04-23 17:54 UTC, take2webservice commented on _ja/tour/polymorphic-methods.md
> +title: ポリモフィズムメソッド
```suggestion
title: ポリモーフフィックメソッド
```

2019-04-23 17:55 UTC, take2webservice commented on _ja/tour/polymorphic-methods.md
> +Scalaのメソッドは値と同様に型によってパラメータ化することができます。構文はジェネリッククラスの構文と同じです。
確かに同じじゃダメですよねw

2019-04-23 17:59 UTC, take2webservice commented on _ja/tour/polymorphic-methods.md
> +2つ目の呼び出し例では必ずしも明示的に型パラメータを渡す必要がないことが判ります。コンパイラはしばしばコンテキストか値引数の型に基づき、型パラメータを推論できます。この例では`"La"`は`String`であり、コンパイラは`A`が`String`でなければならないと気づきます。
言われてみれば、mustには断定的推量の意味があったのだった

2019-04-23 18:00 UTC, merged