Japanese translation of TOUR OF SCALA type-inference
take2webservice/docs.scala-lang pull request #34
Opened 2019-04-11 12:58 UTC by take2webservice

2019-04-24 16:38 UTC, tockri requested changes
ちょっと嫌な文がいくつかありましたね。

2019-04-24 16:38 UTC, tockri commented on _ja/tour/type-inference.md
> +title: 型インターフェイス
```suggestion
title: 型推論
```
たいへんだw

2019-04-24 16:38 UTC, tockri commented on _ja/tour/type-inference.md
> +Scalaコンパイラはしばしば式の型推論するので、明示的に型を宣言する必要はありません。
```suggestion
Scalaコンパイラが式の型を推論できることが多いので、明示的に型を宣言する必要はありません。
```
できないこともあるからねーという含みをもたせるoftenですね。alwaysじゃなくて。

2019-04-24 16:38 UTC, tockri commented on _ja/tour/type-inference.md
> +以下のような場合は型パラメータを指定することは強制されません。それは[ポリモーフフィックメソッド](polymorphic-methods.html)が呼ばれる時や[ジェネリッククラス](generic-classes.html) がインスタンス化される時です。Scalaコンパイラはそのようなコンテキスト、メソッドやコンストラクタのパラメータ型に型パラメータが実際になければ推論します。
```suggestion
次のような場合は型パラメータを指定することは強制されません。[ポリモーフフィックメソッド](polymorphic-methods.html)が呼ばれる時や[ジェネリッククラス](generic-classes.html) がインスタンス化される時です。Scalaコンパイラは文脈あるいはメソッドやコンストラクタの実際の引数から、指定されていない型パラメータを推論します。
```
文脈って言ってるのは、たとえば変数に代入する場合とかですね。
```
def someMethod[A]():A = .....
val x:Int = someMethod()
```
って呼ぶとA = Intと推論する、みたいなの。

2019-04-24 16:38 UTC, tockri commented on _ja/tour/type-inference.md
> +コンパイラはメソッドのパラメータを決して推論しません。しかしながら、確かなケースとして、無名関数のパラメータ型を推論できます。それは関数に引数が渡された場合です。
```suggestion
コンパイラはメソッドのパラメータを決して推論しません。しかし、関数が引数として渡されている場合は、無名関数のパラメータ型を推論できます。
```
in certain casesは「ある場合は」ですが、その後 when ... と、その場合が具体的に書いてあるので、さっき言った「ある場合」というのはつまりこの場合ですよ、という構造なので、もう混ぜちゃってみました。

2019-04-24 16:38 UTC, tockri commented on _ja/tour/type-inference.md
> +mapのパラメータは`f: A => B`です。`Seq`に整数値を渡すため、コンパイラは`A`が`Int`だと気づきます(つまり、あの`x`は整数です)。そのためコンパイラは`x * 2`から`B`は型`Int`であると推論できます。
```suggestion
mapのパラメータは`f: A => B`です。`Seq`の中に整数が入っているので、コンパイラは`A`が`Int`だと知っています(つまり、この`x`は整数です)。したがってコンパイラは`x * 2`から`B`が型`Int`であると推論できます。
```
「気づく」だとknowよりfindのほうがふさわしいですね。find は not know から know に状態遷移することです。
thatは「私」と「あなた」から離れている場所、を表しますが、日本語の文で「さっきの例に出てきたx」のことを「あのx」というとちょっと違うので、「この」がいいと思います。

2019-04-24 16:38 UTC, tockri commented on _ja/tour/type-inference.md
> +一般的にパブリックなAPIではメンバーの型宣言を公開するとより読みやすいと考えられます。そのため、コードをユーザーに公開するAPIならば型を明白にすることお勧めします。
```suggestion
一般的には、パブリックなAPIで公開されているメンバーの型を宣言したほうが読みやすいと考えられています。そのため、ユーザーに公開するAPIではあなたのコードの型を明示することをお勧めします。
```

2019-04-24 16:38 UTC, tockri commented on _ja/tour/type-inference.md
> +こちらはコンパイルできません。`obj`の型推論は`Null`だからです。その型の唯一の値が`null`だから、他の値を割り当てられません。
```suggestion
こちらはコンパイルできません。`obj`に推論された型は`Null`だからです。その型の唯一の値が`null`なので、他の値を代入できれません。
```

2019-04-28 04:12 UTC, take2webservice commented on _ja/tour/type-inference.md
> +title: 型インターフェイス
あ”あ”あ”あ”あ”あ”

2019-04-28 04:14 UTC, take2webservice commented on _ja/tour/type-inference.md
> +Scalaコンパイラはしばしば式の型推論するので、明示的に型を宣言する必要はありません。
ムー難しい

2019-04-28 04:16 UTC, take2webservice commented on _ja/tour/type-inference.md
> +以下のような場合は型パラメータを指定することは強制されません。それは[ポリモーフフィックメソッド](polymorphic-methods.html)が呼ばれる時や[ジェネリッククラス](generic-classes.html) がインスタンス化される時です。Scalaコンパイラはそのようなコンテキスト、メソッドやコンストラクタのパラメータ型に型パラメータが実際になければ推論します。
なるほどなるほど！

2019-04-28 04:31 UTC, take2webservice commented on _ja/tour/type-inference.md
> +mapのパラメータは`f: A => B`です。`Seq`に整数値を渡すため、コンパイラは`A`が`Int`だと気づきます(つまり、あの`x`は整数です)。そのためコンパイラは`x * 2`から`B`は型`Int`であると推論できます。
なるほど、道理でいつもThatを`あの`で訳していて気持ち悪いわけですね！

2019-04-28 04:33 UTC, merged