Japanese translation of TOUR OF SCALA operators
take2webservice/docs.scala-lang pull request #36
Opened 2019-04-11 13:38 UTC by take2webservice

2019-04-25 14:01 UTC, tockri requested changes
演算子の優先順位って、文字の順番が決まってたんだ・・・！

2019-04-25 14:01 UTC, tockri commented on _ja/tour/operators.md
> +title: オペレータ
```suggestion
title: 演算子
```
一般的にはoperatorの日本語訳は演算子かなって思います。

2019-04-25 14:01 UTC, tockri commented on _ja/tour/operators.md
> +Scalaではオペレーターはメソッドです。1つのパラメータを持つメソッドであれば*中置オペレータ*として使えます。例えば、`+`はドット記法で呼び出せます。
```suggestion
Scalaではオペレーターはメソッドです。1つのパラメータを持つメソッドであれば*中置演算子*として使えます。例えば、`+`はドット記法で呼び出せます。
```

2019-04-25 14:01 UTC, tockri commented on _ja/tour/operators.md
> +## オペレータの定義方法と使い方
```suggestion
## 演算子の定義方法と使い方
```

2019-04-25 14:01 UTC, tockri commented on _ja/tour/operators.md
> +有効な識別子であればオペレータとして使用できます。これは `add`のような名前と`+`のようなシンボルも含みます。
```suggestion
有効な識別子であれば演算子として使用できます。これは `add`のような名前と`+`のような記号も含みます。
```

2019-04-25 14:01 UTC, tockri commented on _ja/tour/operators.md
> +この時、`and`と`or`を中置オペレータとして使えます。
```suggestion
この時、`and`と`or`を中置演算子として使えます。
```

2019-04-25 14:01 UTC, tockri commented on _ja/tour/operators.md
> +これにより`xor`の定義をより読みやすくします。
```suggestion
これにより`xor`の定義がより読みやすくなります。
```

2019-04-25 14:01 UTC, tockri commented on _ja/tour/operators.md
> +式が複数のオペレータを使う時、最初の記号の優先度に基づきオペレータは評価されます。
```suggestion
式が複数の演算子を使う時、それらの演算子は最初の文字の（以下に挙げる）優先度に基づき評価されます。
```
「:」って日本語にないからいつも困りますね。あとここのcharacterはStringの1文字目って意味だけど、たぶんすぐ下のcharacterは記号で合ってるたぶん。いいのかこんなんで

2019-04-25 14:01 UTC, tockri commented on _ja/tour/operators.md
> +これはあなたが定義した関数にも適用できます。
```suggestion
これはあなたが定義した関数にも適用できます。
たとえば、以下の式
```

2019-04-28 04:54 UTC, take2webservice commented on _ja/tour/operators.md
> +title: オペレータ
なるほど！

2019-04-28 04:57 UTC, take2webservice commented on _ja/tour/operators.md
> +式が複数のオペレータを使う時、最初の記号の優先度に基づきオペレータは評価されます。
やっぱ「:」も訳してあげたほうが親切ですよね。
ぬぅー、characterも訳し方むずかしい…

2019-04-28 04:58 UTC, merged