Japanese translation of TOUR OF SCALA by-name-parameters
take2webservice/docs.scala-lang pull request #37
Opened 2019-04-11 14:28 UTC by take2webservice

`By-name parameters`と`by-value parameters`の訳を`名前付きパラメータ`と`値付きパラメータ`と訳したのですが、すごく間違ってる気がします…

2019-04-25 23:17 UTC, tockri requested changes
この機能、名前渡しって言う名前があるんですねー。単に関数を渡してるだけとしか思ってなかった。「
call by name」でググると「名前渡し」とか「名前呼び」と出てきました。

2019-04-25 23:17 UTC, tockri commented on _ja/tour/by-name-parameters.md
> +title: 名前付きパラメータ
```suggestion
title: 名前渡しパラメータ
```
最近話題の"call by reference"は参照渡し、"call by value"は値渡しなので、"call by name"は名前渡しですね。

2019-04-25 23:17 UTC, tockri commented on _ja/tour/by-name-parameters.md
> +*名前付きパラメータ*は使用された時に評価されます。それらは*値つきパラメータ*とは対照的です。名前で呼び出せるパラメータを作るには、単純に`=>`を型の前につけます。
```suggestion
*名前渡しのパラメータ*は使用された時に評価されます。それらは*値渡しパラメータ*とは対照的です。名前渡しのパラメータを作るには、単純に`=>`を型の前につけます。
```

2019-04-25 23:17 UTC, tockri commented on _ja/tour/by-name-parameters.md
> +名前付きパラメータの利点は関数本体の中で使わなければ評価されない点です。一方で、値付きパラメータの利点は1度だけ評価される点です。
```suggestion
名前渡しパラメータの利点は関数本体の中で使わなければ評価されない点です。一方で、値渡しパラメータの利点は1度しか評価されない点です。
```

2019-04-25 23:17 UTC, tockri commented on _ja/tour/by-name-parameters.md
> +メソッド`whileLoop`は条件とループの本体を受け取るために複数パラメータリストを使います。もし`condition`がtrueならば、`body`は実行され、そしてwhileループの再帰呼び出しがされます。`condition`がfalseならば、bodyは決して評価されません。それは`body`の型の前に`=>`をつけたからです。
```suggestion
このメソッド`whileLoop`は条件とループの本体を受け取るために複数パラメータリストを使います。もし`condition`がtrueならば、`body`が実行され、次にwhileLoopが再帰的に呼ばれます。`condition`がfalseならば、bodyは決して評価されません。それは`body`の型の前に`=>`をつけたからです。
```

2019-04-25 23:17 UTC, tockri commented on _ja/tour/by-name-parameters.md
> +ここで、`condition`に`i > 0`、`body`に`println(i); i-= 1`を渡した場合、多くの言語では一般的なwhileループと同じ振る舞いをします。
```suggestion
ここで、`condition`に`i > 0`、`body`に`println(i); i-= 1`を渡した場合、多くの言語で一般的なwhileループと同じ振る舞いをします。
```

2019-04-25 23:17 UTC, tockri commented on _ja/tour/by-name-parameters.md
> +パラメータが使われるまで評価を遅延させる機能はパフォーマンスを助けます。それはパラメータを評価するための計算が集約的な場合やURLの取得のような時間がかかるコードブロックの場合です。
```suggestion
パラメータが使われるまで評価を遅延する機能はパフォーマンスの助けになることがあります。それはパラメータを評価するのに多くの計算が必要な場合や、URLの取得のような時間がかかるコードブロックの場合です。
```
「こと」を増やしてしまった…でも「助けます」だと日本語であまり言わない形なので「Redbullは翼をさずける」みたいな直訳感がどうしても。

2019-04-28 04:58 UTC, take2webservice commented
あー、名前渡しと値渡しのことだったんですね！！

2019-04-28 05:10 UTC, merged