Japanese translation of TOUR OF SCALA packages-and-imports
take2webservice/docs.scala-lang pull request #41
Opened 2019-04-11 19:03 UTC by take2webservice

2019-04-28 16:21 UTC, tockri requested changes
Scalaのパッケージとディレクトリの関係は、Javaみたいな強制力ぜんぜんなくて、どのディレクトリにどのパッケージがあってもいいんですが、ときどき謎の間違いがおきますね。

2019-04-28 16:21 UTC, tockri commented on _ja/tour/packages-and-imports.md
> +パッケージとScalaファイルが含まれるディレクトリは同じ名前をつける習慣があります。しかし、Scalaはファイルのレイアウトを認知できません。`package users`のsbtプロジェクトのディレクトリ構成はこのように見えます。
```suggestion
パッケージとScalaファイルが含まれるディレクトリは同じ名前をつける習慣があります。しかし、Scalaはファイルのレイアウトには関知しません。`package users`を含むsbtプロジェクトのディレクトリ構成はこのようになるかもしれません。
```

2019-04-28 16:21 UTC, tockri commented on _ja/tour/packages-and-imports.md
> +`users`ディレクトリがどのように`scala`ディレクトリの中にあり、Scalaファイルがどのようにパッケージ内にあるのかに注意してください。パッケージ内のいずれのScalaファイルも同じパッケージ宣言がされます。他のパッケージ宣言の方法は波括弧を使います。
```suggestion
`users`ディレクトリがどのように`scala`ディレクトリの中にあり、複数のScalaファイルがどのようにパッケージ内にあるのかに注意してください。パッケージ内のScalaファイルは同じパッケージ宣言を持ちます。パッケージ宣言の他の方法は波括弧を使い以下のようにします。
```

2019-04-28 16:21 UTC, tockri commented on _ja/tour/packages-and-imports.md
> +見ての通り、この方法はパッケージのネストができ、より大きいスコープとカプセル化のコントロールができます。
```suggestion
見ての通り、この方法はパッケージのネストができ、スコープとカプセル化をより強くコントロールできます。
```

2019-04-28 16:21 UTC, tockri commented on _ja/tour/packages-and-imports.md
> +`import`句は他パッケージのメンバー（クラス、トレイト、関数など）にアクセスするためのものです。同じパッケージのメンバーにアクセスするには`import`句は必要ありません。import句は選択的です。
```suggestion
`import`句は他パッケージのメンバー（クラス、トレイト、関数など）にアクセスするためのものです。同じパッケージのメンバーにアクセスするには`import`句は必要ありません。import句は以下のどれでも使えます。
```

2019-04-28 16:21 UTC, tockri commented on _ja/tour/packages-and-imports.md
> +ScalaのJavaと異なる利用方法の1つはインポートがどこでも使える点です。
```suggestion
ScalaのJavaと異なる点の1つはインポートがどこでも使える点です。
```
wayは利用の方法とは限らないので。

2019-04-29 06:55 UTC, take2webservice commented on _ja/tour/packages-and-imports.md
> +ScalaのJavaと異なる利用方法の1つはインポートがどこでも使える点です。
なんと！！

2019-04-29 06:55 UTC, merged